version: "3"

services:

  sqlite:
    image: sqlite:latest
    environment:
      SQLITE_DATABASE: mydb
    container_name: sqlite
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: sqlite
    networks:
      - my-network

  fastapi:
    build: fastapi/
    ports:
      - 8000:8000
    environment:
      - DB_HOST: sqlite
    container_name: fastapi
    networks:
      - my-network

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    container_name: streamlit
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
